cookie:
  expiry_days: 0
credentials:
  usernames:
    pratham:
      email: prathamrao001@gmail.com
      first_name: Pratham
      last_name: Rao
      logged_in: false
      password: $2b$12$0n4lSQf06o/tk.xYBeASBOY5kva.3BFAxfsoiYYwTi5E4Uot7YZ1m
      password_hint: P1
      roles: null
    rahul:
      email: rahul.j.jacob@gmail.com
      first_name: Rahul
      last_name: Jacob
      logged_in: false
      password: $2b$12$g4A/NKrpWqFiwlE8tYnAGeg7ZJHFU3uDl7S0GpNOS8h8xX0m6Z0Gq
      password_hint: R1
      roles: null
